/*
 *  Print Dialog for Canon LIPS/PS/LIPSLX/UFR2/CAPT Printer.
 *  Copyright (C) 2004-2011 Canon Inc.
 *  All rights reserved.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef	_PPDKEYS_H_
#define	_PPDKEYS_H_


#define kPPD_Items_PageSize							"PageSize"
#define kPPD_Items_MediaType						"MediaType"
#define kPPD_Items_InputSlot						"InputSlot"
#define kPPD_Items_OutputBin						"OutputBin"
#define kPPD_Items_Duplex							"Duplex"
#define kPPD_Items_Booklet							"Booklet"
#define kPPD_Items_BindEdge							"BindEdge"
#define kPPD_Items_CNOutputPartition				"CNOutputPartition"
#define kPPD_Items_Collate							"Collate"
#define kPPD_Items_StapleLocation					"StapleLocation"
#define kPPD_Items_CNSaddleStitch					"CNSaddleStitch"
#define kPPD_Items_CNTrimming						"CNTrimming"
#define kPPD_Items_CNZfolding						"CNZfolding"
#define kPPD_Items_CNPunch							"CNPunch"
#define kPPD_Items_CNInserter						"CNInserter"
#define kPPD_Items_Resolution						"Resolution"
#define kPPD_Items_CNColorMode						"CNColorMode"
#define kPPD_Items_CNHalftone						"CNHalftone"
#define kPPD_Items_CNBlackSubstitute				"CNBlackSubstitute"
#define kPPD_Items_CNPureBlackProcess				"CNPureBlackProcess"
#define kPPD_Items_CNTonerSaving					"CNTonerSaving"
#define kPPD_Items_CNFinisher						"CNFinisher"
#define kPPD_Items_CNPuncher						"CNPuncher"
#define kPPD_Items_CNFolder							"CNFolder"
#define kPPD_Items_CNInsertUnit						"CNInsertUnit"
#define kPPD_Items_CNTrimmer						"CNTrimmer"
#define kPPD_Items_CNDuplexUnit						"CNDuplexUnit"
#define kPPD_Items_CNJobExecMode					"CNJobExecMode"
#define kPPD_Items_CNTonerDensity					"CNTonerDensity"
#define kPPD_Items_CNSuperSmooth					"CNSuperSmooth"
#define kPPD_Items_CNFixingMode						"CNFixingMode"
#define kPPD_Items_CNBackPaperPrint					"CNBackPaperPrint"
#define kPPD_Items_CNOutputFace						"CNOutputFace"
#define kPPD_Items_CNRotatePrint					"CNRotatePrint"
#define kPPD_Items_CNImageSpecialProcess			"CNImageSpecialProcess"
#define kPPD_Items_CNCopySetNumbering				"CNCopySetNumbering"
#define kPPD_Items_CNDraftMode						"CNDraftMode"
#define kPPD_Items_CNInterleafSheet					"CNInterleafSheet"
#define kPPD_Items_CNInterleafMediaType				"CNInterleafMediaType"
#define kPPD_Items_CNInterleafPrint					"CNInterleafPrint"
#define kPPD_Items_CNSrcOption						"CNSrcOption"
#define kPPD_Items_CNColorHalftone					"CNColorHalftone"
#define kPPD_Items_CNCTonerDensity					"CNCTonerDensity"
#define kPPD_Items_CNMTonerDensity					"CNMTonerDensity"
#define kPPD_Items_CNYTonerDensity					"CNYTonerDensity"
#define kPPD_Items_CNKeepGray						"CNKeepGray"
#define kPPD_Items_CNSkipBlank						"CNSkipBlank"
#define kPPD_Items_CNDetectPaperSize				"CNDetectPaperSize"
#define kPPD_Items_CNPureBlackText					"CNPureBlackText"
#define kPPD_Items_CNBlackOverprint					"CNBlackOverprint"
#define kPPD_Items_CNRGBSourceProfile				"CNRGBSourceProfile"
#define kPPD_Items_CNRGBMatchingMethod				"CNRGBMatchingMethod"
#define kPPD_Items_CNRGBPureBlackProcess			"CNRGBPureBlackProcess"
#define kPPD_Items_CNCMYKSimulationProfile			"CNCMYKSimulationProfile"
#define kPPD_Items_CNUseGrayScaleProfile			"CNUseGrayScaleProfile"
#define kPPD_Items_CNOutputProfile					"CNOutputProfile"
#define kPPD_Items_CNGradationSmoothing				"CNGradationSmoothing"
#define kPPD_Items_CNImageRefinement				"CNImageRefinement"
#define kPPD_Items_CNLineRefinement					"CNLineRefinement"
#define kPPD_Items_CNMirrorPrint					"CNMirrorPrint"
#define kPPD_Items_CNSpecialPrintMode				"CNSpecialPrintMode"
#define kPPD_Items_CNPostcardPrinting				"CNPostcardPrinting"
#define kPPD_Items_CNLastPagePrintMode				"CNLastPagePrintMode"
#define kPPD_Items_CNPaperSelection					"CNPaperSelection"
#define kPPD_Items_CNInterleafSlot					"CNInterleafSlot"
#define kPPD_Items_CNContinuePrinting				"CNContinuePrinting"
#define kPPD_Items_CNPostcardPrintMode				"CNPostcardPrintMode"
#define kPPD_Items_CNGradation						"CNGradation"
#define kPPD_Items_CNGradationPrint					"CNGradationPrint"
#define kPPD_Items_CNXColorAdjustment				"CNXColorAdjustment"
#define kPPD_Items_CNYColorAdjustment				"CNYColorAdjustment"
#define kPPD_Items_CNBrightness						"CNBrightness"
#define kPPD_Items_CNContrast						"CNContrast"
#define kPPD_Items_CNImageAdjustment				"CNImageAdjustment"
#define kPPD_Items_CNGraphicsAdjustment				"CNGraphicsAdjustment"
#define kPPD_Items_CNTextAdjustment					"CNTextAdjustment"
#define kPPD_Items_CNMatchingMode					"CNMatchingMode"
#define kPPD_Items_CNMatchingMethod					"CNMatchingMethod"
#define kPPD_Items_CNImageMatchingMethod			"CNImageMatchingMethod"
#define kPPD_Items_CNGraphicsMatchingMethod			"CNGraphicsMatchingMethod"
#define kPPD_Items_CNTextMatchingMethod				"CNTextMatchingMethod"
#define kPPD_Items_CNMonitorProfile					"CNMonitorProfile"
#define kPPD_Items_CNImageMonitorProfile			"CNImageMonitorProfile"
#define kPPD_Items_CNGraphicsMonitorProfile			"CNGraphicsMonitorProfile"
#define kPPD_Items_CNTextMonitorProfile				"CNTextMonitorProfile"
#define kPPD_Items_CNGamma							"CNGamma"
#define kPPD_Items_CNBWHalftone						"CNBWHalftone"
#define kPPD_Items_CNSpotColorMatching				"CNSpotColorMatching"
#define kPPD_Items_CNOHPPrintMode					"CNOHPPrintMode"
#define kPPD_Items_CNAdvancedSmoothing				"CNAdvancedSmoothing"
#define kPPD_Items_CNSetFrontSheet					"CNSetFrontSheet"
#define kPPD_Items_CNFrontPrintOn					"CNFrontPrintOn"
#define kPPD_Items_CNFrontPaperSrc					"CNFrontPaperSrc"
#define kPPD_Items_CNSetBackSheet					"CNSetBackSheet"
#define kPPD_Items_CNBackPrintOn					"CNBackPrintOn"
#define kPPD_Items_CNBackPaperSrc					"CNBackPaperSrc"
#define kPPD_Items_CNUseColorantDensity				"CNUseColorantDensity"
#define kPPD_Items_CNColorantDensity				"CNColorantDensity"


#define kPPD_Items_CNTrayCSetting					"CNTrayCSetting"
#define kPPD_Items_CNSidePaperDeck					"CNSidePaperDeck"
#define kPPD_Items_CNHardDisk						"CNHardDisk"
#define kPPD_Items_CNSpecialFineLineProcess			"CNSpecialFineLineProcess"
#define kPPD_Items_CNShiftStartPrintPosition		"CNShiftStartPrintPosition"
#define kPPD_Items_CNProcessColorMode				"CNProcessColorMode"
#define kPPD_Items_CNDuplexFixMode					"CNDuplexFixMode"
#define kPPD_Items_CNCalibrate						"CNCalibrate"
#define kPPD_Items_CNDuplex							"CNDuplex"
#define kPPD_Items_CNCreep							"CNCreep"
#define kPPD_Items_CNStaple							"CNStaple"
#define kPPD_Items_CNTypeWing						"CNTypeWing"
#define kPPD_Items_CNImageCompression				"CNImageCompression"
#define kPPD_Items_CNDensityFineAdjustment			"CNDensityFineAdjustment"
#define kPPD_Items_CNDensityFineAdjustmentNum		"CNDensityFineAdjustmentNum"
#define kPPD_Items_CNCADMode						"CNCADMode"
#define kPPD_Items_CNGraphicsMode					"CNGraphicsMode"
#define kPPD_Items_CNCompositeOverprint				"CNCompositeOverprint"
#define kPPD_Items_CNCombineColorSeparation			"CNCombineColorSeparation"

#define	kPPD_Items_CNCurlCorrection					"CNCurlCorrection"
#define	kPPD_Items_CNPausePrintingMT				"CNPausePrintingMT"

#define	kPPD_Items_CNAppColorMatching				"CNAppColorMatching"

#define kPPD_Items_CNFeedCustomHorizontally			"CNFeedCustomHorizontally"

#define	kPPD_Items_CNDisplacementCorrection			"CNDisplacementCorrection"
#define	kPPD_Items_CNProgress						"CNProgress"
#define	kPPD_Items_CNNotification					"CNNotification"
#define	kPPD_Items_CNOverlay						"CNOverlay"
#define	kPPD_Items_CNSelectBy						"CNSelectBy"
#define	kPPD_Items_CNOHPPrint						"CNOHPPrint"
#define	kPPD_Items_CNInterleafInputSlot				"CNInterleafInputSlot"
#define	kPPD_Items_CNPrintOtherSide					"CNPrintOtherSide"
#define	kPPD_Items_CNInsertSheet					"CNInsertSheet"
#define	kPPD_Items_CNSheetForInsertion				"CNSheetForInsertion"
#define	kPPD_Items_CNInsertPrintSide				"CNInsertPrintSide"
#define	kPPD_Items_CNInsertInputSlot				"CNInsertInputSlot"
#define	kPPD_Items_CNPrioritizeLineText				"CNPrioritizeLineText"
#define	kPPD_Items_CNUsePSBrightness				"CNUsePSBrightness"
#define	kPPD_Items_CNPSBrightness					"CNPSBrightness"
#define kPPD_Items_CNCollate						"CNCollate"
#define kPPD_Items_CNCfolding						"CNCfolding"
#define kPPD_Items_CNPBindCoversheet				"CNPBindCoversheet"
#define kPPD_Items_CNPBindFinishing					"CNPBindFinishing"
#define kPPD_Items_CNPBindMainPaper					"CNPBindMainPaper"
#define kPPD_Items_CNAdjustTrim						"CNAdjustTrim"
#define kPPD_Items_CNTrustPrint						"CNTrustPrint"
#define kPPD_Items_CNOverlayFormComposition			"CNOverlayFormComposition"
#define kPPD_Items_CNUseSharpness					"CNUseSharpness"
#define kPPD_Items_CNSharpness						"CNSharpness"
#define kPPD_Items_CNTonerDensityAdjustment			"CNTonerDensityAdjustment"
#define kPPD_Items_CNLineControl					"CNLineControl"
#define kPPD_Items_CNSmallSizeCurl					"CNSmallSizeCurl"
#define kPPD_Items_CNAuthenticate					"CNAuthenticate"
#define kPPD_Items_CNUseJobAccount					"CNUseJobAccount"
#define kPPD_Items_CNSendTime						"CNSendTime"
#define kPPD_Items_CNCoverPageMode					"CNCoverPageMode"
#define kPPD_Items_CNInSlotManMediaType				"CNInSlotManMediaType"
#define kPPD_Items_CNInSlot1MediaType				"CNInSlotAMediaType"
#define kPPD_Items_CNInSlot2MediaType				"CNInSlotBMediaType"
#define kPPD_Items_CNInSlot3MediaType				"CNInSlotCMediaType"
#define kPPD_Items_CNInSlot4MediaType				"CNInSlotDMediaType"
#define kPPD_Items_CNSideDeckMediaType				"CNSideDeckMediaType"
#define kPPD_Items_CNUseOutsideLineNum				"CNUseOutsideLineNum"
#define kPPD_Items_CNLineSelection					"CNLineSelection"
#define kPPD_Items_CNFAXNumOfLine					"CNFAXNumOfLine"
#define kPPD_Items_CNSpecID							"CNSpecID"
#define kPPD_Items_CNTotalMemSize					"CNTotalMemSize"
#define kPPD_Items_CNDupUnit						"CNDupUnit"
#define kPPD_Items_CNFAXLineType					"CNFAXLineType"
#define kPPD_Items_CNEnableTrustPrint				"CNEnableTrustPrint"
#define kPPD_Items_CNFinTray						"CNFinTray"
#define kPPD_Items_CNStacker						"CNStacker"
#define kPPD_Items_CNBinderOption					"CNBinderOption"
#define kPPD_Items_CNEnableMultiInserter			"CNEnableMultiInserter"
#define kPPD_Items_CNTonerVolumeAdjustment			"CNTonerVolumeAdjustment"
#define kPPD_Items_CNCopyTray						"CNCopyTray"
#define kPPD_Items_CNCfoldSetting					"CNCfoldSetting"
#define kPPD_Items_CNTabPrintMode					"CNTabPrintMode"
#define kPPD_Items_CNOutputColorSpeed				"CNOutputColorSpeed"
#define kPPD_Items_CNInSlot5MediaType				"CNInSlotEMediaType"
#define kPPD_Items_CNInSlot6MediaType				"CNInSlotFMediaType"
#define kPPD_Items_CNInSlot7MediaType				"CNInSlotGMediaType"
#define kPPD_Items_CNInSlot8MediaType				"CNInSlotHMediaType"
#define kPPD_Items_CNOptionStaple					"CNOptionStaple"

#define kPPD_Items_CNSpecialPrintAdjustmentA		"CNSpecialPrintAdjustmentA"
#define kPPD_Items_CNSpecialPrintAdjustmentB		"CNSpecialPrintAdjustmentB"
#define kPPD_Items_CNRevicePostcard					"CNRevicePostcard"
#define kPPD_Items_CNOutputAdjustment				"CNOutputAdjustment"
#define kPPD_Items_CNSpecialSmooth					"CNSpecialSmooth"
#define kPPD_Items_CNEnableQuick					"CNEnableQuick"
#define kPPD_Items_CNEnableFine						"CNEnableFine"
#define kPPD_Items_CNEnableSuperFine				"CNEnableSuperFine"
#define kPPD_Items_CNFAXDialLine1					"CNFAXDialLineA"
#define kPPD_Items_CNFAXDialLine2					"CNFAXDialLineB"
#define kPPD_Items_CNFAXDialLine3					"CNFAXDialLineC"
#define kPPD_Items_CNWrinklesCorrectionOutput		"CNWrinklesCorrectionOutput"
#define kPPD_Items_CNPdeUseJobAccount				"CNPdeUseJobAccount"
#define kPPD_Items_CNProPuncher						"CNProPuncher"
#define kPPD_Items_CNMultiPunch						"CNMultiPunch"
#define kPPD_Items_CNTopBottomTrimmer				"CNTopBottomTrimmer"
#define kPPD_Items_CNFAXDialLine4					"CNFAXDialLineD"
#define kPPD_Items_CNSaddleUnit						"CNSaddleUnit"
#define kPPD_Items_CNClearCoatingApplication		"CNClearCoatingApplication"
#define kPPD_Items_CNGlossyPlainPaperProc				"CNGlossyPlainPaperProc"
#define kPPD_Items_CNVfolding						"CNVfolding"
#define kPPD_Items_CNHalfFolding					"CNHalfFolding"
#define kPPD_Items_CNAccordionZfolding				"CNAccordionZfolding"
#define kPPD_Items_CNDoubleParallelFolding			"CNDoubleParallelFolding"
#define kPPD_Items_CNHalfFoldSetting				"CNHalfFoldSetting"
#define kPPD_Items_CNAccordionZfoldSetting			"CNAccordionZfoldSetting"
#define kPPD_Items_CNDoubleParallelFoldSetting		"CNDoubleParallelFoldSetting"
#define	kPPD_Items_CNSaddleSetting					"CNSaddleSetting"
#define	kPPD_Items_CNTrapping						"CNTrapping"
#define	kPPD_Items_CNTrapWidth						"CNTrapWidth"
#define	kPPD_Items_CNTrapDensity					"CNTrapDensity"
#define kPPD_Items_CNSizeOverride					"CNSizeOverride"
#define kPPD_Items_CNReverseOrder					"CNReverseOrder"
#define	kPPD_Items_CNDotGain						"CNDotGain"
#define	kPPD_Items_CNGrayConversion					"CNGrayConversion"
#define kPPD_Items_CNPBindCoverSelectBy				"CNPBindCoverSelectBy"
#define kPPD_Items_CNPBindCoverPaperSource			"CNPBindCoverPaperSource"
#define kPPD_Items_CNPBindCoverMediaType			"CNPBindCoverMediaType"
#define kPPD_Items_CNPBindSpecifyFinishingBy		"CNPBindSpecifyFinishingBy"
#define kPPD_Items_CNSpecifyNumOfCopiesStack		"CNSpecifyNumOfCopiesStack"
#define	kPPD_Items_CNRGBMatchingMode				"CNRGBMatchingMode"
#define	kPPD_Items_CNRGBInputLightClrSpace			"CNRGBInputLightClrSpace"
#define	kPPD_Items_CNCMYKMatchingMode				"CNCMYKMatchingMode"
#define	kPPD_Items_CNCMYKInputLightClrSpace			"CNCMYKInputLightClrSpace"
#define kPPD_Items_CNInSlot9MediaType				"CNInSlotIMediaType"
#define kPPD_Items_CNInSlot10MediaType				"CNInSlotJMediaType"
#define kPPD_Items_CNInnerTrimmer					"CNInnerTrimmer"
#define kPPD_Items_CNUserSeparateMode				"CNUserSeparateMode"
#define kPPD_Items_CNSorterFinish					"CNSorterFinish"
#define kPPD_Items_CNStackerFinish					"CNStackerFinish"
#define kPPD_Items_CNBinNameMode					"CNBinNameMode"
#define kPPD_Items_CNEnableSubstituteFont			"CNEnableSubstituteFont"
#define kPPD_Items_CNUseSubstituteFont				"CNUseSubstituteFont"
#define kPPD_Items_CNPrinterFont					"CNPrinterFont"
#define kPPD_Items_CNSubstituteEuroFont				"CNSubstituteEuroFont"
#define kPPD_Items_CNFontRepFamilyCount				"CNFontRepFamilyCount"
#define kPPD_Items_CNFontRepFamilyHost				"CNFontRepFamilyHost"
#define kPPD_Items_CNFontRepFamilyPrn				"CNFontRepFamilyPrn"
#define kPPD_Items_CNFontRepPSCount					"CNFontRepPSCount"
#define kPPD_Items_CNFontRepPSHost					"CNFontRepPSHost"
#define kPPD_Items_CNFontRepPSPrn					"CNFontRepPSPrn"
#define kPPD_Items_CNPdeDisplayAllWarning			"CNPdeDisplayAllWarning"
#define kPPD_Items_CNPlainPaperCurlCorrect			"CNPlainPaperCurlCorrect"
#define kPPD_Items_CNWrinkleEscapeMode				"CNWrinkleEscapeMode"
#define kPPD_Items_CNCurlPaperModeB					"CNCurlPaperModeB"
#define kPPD_Items_CNSpecialPrintAdjustmentC		"CNSpecialPrintAdjustmentC"
#define kPPD_Items_CNSpecialPrintingModeA			"CNSpecialPrintingModeA"
#define kPPD_Items_CNSpecialPrintingModeB			"CNSpecialPrintingModeB"
#define kPPD_Items_CNBarCode						"CNBarCode"
#define kPPD_Items_CNWhiteGap						"CNWhiteGap"
#define kPPD_Items_CNPrintImageAdjustment			"CNPrintImageAdjustment"
#define kPPD_Items_CNDeviceType			"CNDeviceType"
#define kPPD_Items_CNFoldSetting			"CNFoldSetting"
#define kPPD_Items_CNPrintStyle				"CNPrintStyle"
#define kPPD_Items_CNFoldDetail				"CNFoldDetail"
#define kPPD_Items_CNFeedAFiveVertically			"CNFeedAFiveVertically"
#define kPPD_Items_CNSpecialPrintAdjustment			"CNSpecialPrintAdjustment"

#define kPPD_Items_Device_SelectBy					"SelectBy"
#define kPPD_Items_Device_Booklet					"Booklet"
#define kPPD_Items_Device_CNDocName					"CNDocName"
#define kPPD_Items_Device_CNMailBox					"CNMailBox"
#define kPPD_Items_Device_CNBindEdgeShift			"CNBindEdgeShift"
#define kPPD_Items_Device_CNUsrName					"CNUsrName"
#define kPPD_Items_Device_CNSecuredPrint			"CNSecuredPrint"
#define kPPD_Items_Device_CNJobAccount				"CNJobAccount"
#define kPPD_Items_Device_CNStartingNumber			"CNStartingNumber"

#define kPPD_Items_Device_CNShiftUpwards			"CNShiftUpwards"
#define kPPD_Items_Device_CNShiftRight				"CNShiftRight"
#define kPPD_Items_Device_CNShiftFrLongEdge			"CNShiftFrLongEdge"
#define kPPD_Items_Device_CNShiftFrShortEdge		"CNShiftFrShortEdge"
#define kPPD_Items_Device_CNShiftBkLongEdge			"CNShiftBkLongEdge"
#define kPPD_Items_Device_CNShiftBkShortEdge		"CNShiftBkShortEdge"
#define kPPD_Items_Device_CNJobNote					"CNJobNote"
#define kPPD_Items_Device_CNJobDetails				"CNJobDetails"
#define kPPD_Items_Device_CNOffsetNum				"CNOffsetNum"

#define	kPPD_Items_Device_CNInputSelect				"CNInputSelect"

#define	kPPD_Items_CNGutterShiftNum					"CNGutterShiftNum"
#define kPPD_Items_Device_JobAccount				"JobAccount"
#define	kPPD_Items_Device_CNDisableJobAccountingBW	"CNDisableJobAccountingBW"
#define	kPPD_Items_Device_CNMaxDocStr				"CNMaxDocStr"
#define	kPPD_Items_Device_CNTabShift				"CNTabShift"
#define	kPPD_Items_Device_CNMediaBrandList			"CNMediaBrandList"
#define	kPPD_Items_Device_CNMediaBrand				"CNMediaBrand"
#define	kPPD_Items_Device_CNMediaLibraryID			"CNMediaLibraryID"
#define	kPPD_Items_Device_CNMediaShape				"CNMediaShape"
#define	kPPD_Items_Device_CNInsertMediaBrandList	"CNInsertMediaBrandList"
#define	kPPD_Items_Device_CNInsertMediaBrand		"CNInsertMediaBrand"
#define	kPPD_Items_Device_CNInsertMediaLibraryID	"CNInsertMediaLibraryID"
#define	kPPD_Items_Device_CNInterleafMediaBrandList	"CNInterleafMediaBrandList"
#define	kPPD_Items_Device_CNInterleafMediaBrand		"CNInterleafMediaBrand"
#define	kPPD_Items_Device_CNInterleafMediaLibraryID	"CNInterleafMediaLibraryID"
#define	kPPD_Items_Device_CNInsertTabShift			"CNInsertTabShift"
#define	kPPD_Items_Device_CNInsertPos				"CNInsertPos"
#define	kPPD_Items_Device_CNInsertPosPaperSource	"CNInsertPosPaperSource"
#define	kPPD_Items_Device_CNInsertPosPrinton		"CNInsertPosPrinton"
#define	kPPD_Items_Device_CNTabInsertPos			"CNTabInsertPos"
#define	kPPD_Items_Device_CNTabInsertPosPaperSource	"CNTabInsertPosPaperSource"
#define	kPPD_Items_Device_CNTabInsertPosPrinton		"CNTabInsertPosPrinton"
#define kPPD_Items_Device_CNOverlayFileName			"CNOverlayFileName"
#define kPPD_Items_Device_CNFormHandle				"CNFormHandle"
#define kPPD_Items_Device_CNMailBoxNum				"CNMaxBoxNum"
#define kPPD_Items_Device_CNAdjustTrimNum			"CNAdjustTrimNum"
#define kPPD_Items_Device_CNMaxInsertCount			"CNMaxInsertCount"
#define kPPD_Items_Device_CNShiftStartPrintPosType	"CNShiftStartPrintPosType"
#define kPPD_Items_Device_CNSendTimeNum				"CNSendTimeNum"
#define kPPD_Items_Device_CNOutsideLineNumber		"CNOutsideLineNumber"
#define	kPPD_Items_Device_CNRecipientName			"CNRecipientName"
#define	kPPD_Items_Device_CNCompany					"CNCompany"
#define	kPPD_Items_Device_CNDepartment				"CNDepartment"
#define	kPPD_Items_Device_CNDialNumber				"CNDialNumber"
#define	kPPD_Items_Device_CNFCodeNumber				"CNFCodeNumber"
#define	kPPD_Items_Device_CNPassword				"CNPassword"
#define	kPPD_Items_Device_CNSubAddress				"CNSubAddress"
#define	kPPD_Items_Device_CNAddressCount			"CNAddressCount"
#define	kPPD_Items_Device_CNSender					"CNSender"
#define	kPPD_Items_Device_CNCoverPagePath			"CNCoverPagePath"
#define kPPD_Items_Device_CNAdjustForeTrimNum			"CNAdjustForeTrimNum"
#define kPPD_Items_Device_CNAdjustTopBottomTrimNum		"CNAdjustTopBottomTrimNum"
#define	kPPD_Items_Device_CNFeedPaperName				"CNFeedPaperName"
#define	kPPD_Items_Device_CNPBindCoverMediaLibraryID	"CNPBindCoverMediaLibraryID"
#define	kPPD_Items_Device_CNPBindFinishForeTrimNum		"CNPBindFinishForeTrimNum"
#define	kPPD_Items_Device_CNPBindFinishTopBottomTrimNum	"CNPBindFinishTopBottomTrimNum"
#define	kPPD_Items_Device_CNStackCopiesNum				"CNStackCopiesNum"
#define	kPPD_Items_Device_CNBinName						"CNBinName"
#define	kPPD_Items_Device_CNBinNameArray				"CNBinNameArray"


#define	kPPD_Items_CNMAXGutterShiftNum				"CNMAXGutterShiftNum"
#define	kPPD_Items_CNMINGutterShiftNum				"CNMINGutterShiftNum"
#define	kPPD_Items_CNDefaultGutterShiftNum				"CNDefaultGutterShiftNum"
#define kPPD_Items_CNUITrimValMax			"CNUITrimValMax"
#define kPPD_Items_CNUITrimValMin			"CNUITrimValMin"
#define kPPD_Items_CNUIAdjustTrimNumDefault		"CNUIAdjustTrimNumDefault"
#define kPPD_Items_EnableCNOffsetNum			"EnableCNOffsetNum"
#define kPPD_Items_CNUIOffsetMax			"CNUIOffsetMax"
#define kPPD_Items_CNFinDetails			"CNFinDetails"
#define kPPD_Items_CNShiftPositionMin		"CNShiftPositionMin"
#define kPPD_Items_CNShiftPositionMax		"CNShiftPositionMax"
#define kPPD_Items_CNUITopBottomTrimValMax				"CNUITopBottomTrimValMax"
#define kPPD_Items_CNUITopBottomTrimValMin				"CNUITopBottomTrimValMin"
#define kPPD_Items_CNUIAdjustTopBottomTrimNumDefault	"CNUIAdjustTopBottomTrimNumDefault"
#define kPPD_Items_CNUIPBindFinForeTrimValMin			"CNUIPBindFinForeTrimValMin"
#define kPPD_Items_CNUIPBindFinForeTrimValMax			"CNUIPBindFinForeTrimValMax"
#define kPPD_Items_CNUIPBindFinForeTrimValInchMin		"CNUIPBindFinForeTrimValInchMin"
#define kPPD_Items_CNUIPBindFinForeTrimValInchMax		"CNUIPBindFinForeTrimValInchMax"
#define kPPD_Items_CNUIPBindFinForeTrimNumDefault		"CNUIPBindFinForeTrimNumDefault"
#define kPPD_Items_CNUIPBindFinTopBottomTrimValMin		"CNUIPBindFinTopBottomTrimValMin"
#define kPPD_Items_CNUIPBindFinTopBottomTrimValMax		"CNUIPBindFinTopBottomTrimValMax"
#define kPPD_Items_CNUIPBindFinTopBottomTrimValInchMin	"CNUIPBindFinTopBottomTrimValInchMin"
#define kPPD_Items_CNUIPBindFinTopBottomTrimValInchMax	"CNUIPBindFinTopBottomTrimValInchMax"
#define kPPD_Items_CNUIPBindFinTopBottomTrimNumDefault	"CNUIPBindFinTopBottomTrimNumDefault"
#define kPPD_Items_CNUIPaperSourceType			"CNUIPaperSourceType"
#define kPPD_Items_CNUIStapleLocationType		"CNUIStapleLocationType"

#define kPPD_Items_Common_CNCopies					"CNCopies"
#define kPPD_Items_Common_page_set					"page-set"
#define kPPD_Items_Common_page_ranges				"page-ranges"
#define kPPD_Items_Common_outputorder				"outputorder"
#define kPPD_Items_Common_number_up					"number-up"
#define kPPD_Items_Common_orientation_requested		"orientation-requested"
#define kPPD_Items_Common_brightness				"brightness"
#define kPPD_Items_Common_gamma						"gamma"
#define kPPD_Items_Common_job_sheets_start			"job-sheets-start"
#define kPPD_Items_Common_job_sheets_end			"job-sheets-end"
#define kPPD_Items_Common_PrinterName				"PrinterName"
#define kPPD_Items_Common_Filter					"Filter"
#define kPPD_Items_Common_media						"media"
#define kPPD_Items_Common_mirror					"mirror"
#define kPPD_Items_Common_CNQueueDescription		"CNQueueDescription"
#define kPPD_Items_Common_CNHostAddresIPV4			"CNHostAddresIPV4"
#define kPPD_Items_Common_CNHostAddresIPV6			"CNHostAddresIPV6"

#define kPPD_Items_Common_CNApplicationProcessName	"CNApplicationProcessName"
#define kPPD_Items_Common_CNApplicationBundleName	"CNApplicationBundleName"
#define kPPD_Items_Common_CNApplicationBundleVersion	"CNApplicationBundleVersion"

#define kPPD_Items_Image_hue						"hue"
#define kPPD_Items_Image_saturation					"saturation"
#define kPPD_Items_Image_ppi						"ppi"
#define kPPD_Items_Image_scaling					"scaling"
#define kPPD_Items_Image_natural_scaling			"natural-scaling"
#define kPPD_Items_Image_position					"position"

#define kPPD_Items_Text_cpi							"cpi"
#define kPPD_Items_Text_lpi							"lpi"
#define kPPD_Items_Text_columns						"columns"
#define kPPD_Items_Text_page_left					"page-left"
#define kPPD_Items_Text_page_right					"page-right"
#define kPPD_Items_Text_page_top					"page-top"
#define kPPD_Items_Text_page_bottom					"page-bottom"
#define kPPD_Items_Text_prettyprint					"prettyprint"

#define kPPD_Items_Hgpl_blackplot					"blackplot"
#define kPPD_Items_Hgpl_fitplot						"fitplot"
#define kPPD_Items_Hgpl_penwidth					"penwidth"


#define kPPD_Items_MediaBrand_ID					"ID"
#define kPPD_Items_MediaBrand_Name					"NAME"
#define kPPD_Items_MediaBrand_Weight				"WEIGHT"
#define kPPD_Items_MediaBrand_Surface				"SURFACE"
#define kPPD_Items_MediaBrand_Shape					"SHAPE"
#define kPPD_Items_MediaBrand_Color					"COLOR"

#define kPPD_Items_MediaBrand_WeightMin				"WEIGHTMIN"
#define kPPD_Items_MediaBrand_WeightMax				"WEIGHTMAX"

#define kPPD_Items_CNLoginName						"CNLoginName"
#define kPPD_Items_CNSystemEncoding					"CNSystemEncoding"
#define kPPD_Items_CNPDEUserName					"CNPDEUserName"
#define kPPD_Items_CNInfo_BiDirection				"CNInfo_BiDirection"
#define kPPD_Items_CNInfo_UseValidate				"CNInfo_UseValidate"

#endif
