<?xml version="1.0"?>
<KeyTextList>
<Item key="CNEnableTrustPrint">Secure Printing Function of Device</Item>
<Item key="MediaType_PlainPaper1">Plain Paper 1</Item>
<Item key="MediaType_PlainPaper2">Plain Paper 2</Item>
<Item key="MediaType_RECYCLED1">Recycled Paper 1</Item>
<Item key="MediaType_RECYCLED2">Recycled Paper 2</Item>
<Item key="MediaType_HEAVY4">Heavy Paper 4</Item>
<Item key="MediaType_TRACING">Tracing</Item>
<Item key="MediaType_PlainPaperL">Thin</Item>
<Item key="MediaType_1SIDECOATED1">1-sided Coated 1</Item>
<Item key="MediaType_1SIDECOATED2">1-sided Coated 2</Item>
<Item key="MediaType_1SIDECOATED3">1-sided Coated 3</Item>
<Item key="MediaType_1SIDECOATED4">1-sided Coated 4</Item>
<Item key="MediaType_2SIDECOATED1">2-sided Coated 1</Item>
<Item key="MediaType_2SIDECOATED2">2-sided Coated 2</Item>
<Item key="MediaType_2SIDECOATED3">2-sided Coated 3</Item>
<Item key="MediaType_2SIDECOATED4">2-sided Coated 4</Item>
<Item key="MediaType_EMBOSS1">Texture Paper 1</Item>
<Item key="MediaType_EMBOSS2">Texture Paper 2</Item>
<Item key="MediaType_EMBOSS3">Texture Paper 3</Item>
<Item key="MediaType_EMBOSS4">Texture Paper 4</Item>
<Item key="InputSlot_SideDeck">Drawer 5 </Item>
<Item key="InputSlot_PodDeck">Drawer 5  </Item>
<Item key="CNInterleafMediaType_PlainPaper1">Plain Paper 1</Item>
<Item key="CNInterleafMediaType_PlainPaper2">Plain Paper 2</Item>
<Item key="CNInterleafMediaType_RECYCLED1">Recycled Paper 1</Item>
<Item key="CNInterleafMediaType_RECYCLED2">Recycled Paper 2</Item>
<Item key="CNInterleafMediaType_HEAVY4">Heavy Paper 4</Item>
<Item key="CNInterleafMediaType_PlainPaperL">Thin</Item>
<Item key="CNInterleafMediaType_1SIDECOATED1">1-sided Coated 1</Item>
<Item key="CNInterleafMediaType_1SIDECOATED2">1-sided Coated 2</Item>
<Item key="CNInterleafMediaType_1SIDECOATED3">1-sided Coated 3</Item>
<Item key="CNInterleafMediaType_1SIDECOATED4">1-sided Coated 4</Item>
<Item key="CNInterleafMediaType_2SIDECOATED1">2-sided Coated 1</Item>
<Item key="CNInterleafMediaType_2SIDECOATED2">2-sided Coated 2</Item>
<Item key="CNInterleafMediaType_2SIDECOATED3">2-sided Coated 3</Item>
<Item key="CNInterleafMediaType_2SIDECOATED4">2-sided Coated 4</Item>
<Item key="CNInterleafMediaType_EMBOSS1">Texture Paper 1</Item>
<Item key="CNInterleafMediaType_EMBOSS2">Texture Paper 2</Item>
<Item key="CNInterleafMediaType_EMBOSS3">Texture Paper 3</Item>
<Item key="CNInterleafMediaType_EMBOSS4">Texture Paper 4</Item>
<Item key="CNFrontPaperSrc_SideDeck">Drawer 5 </Item>
<Item key="CNFrontPaperSrc_PodDeck">Drawer 5  </Item>
<Item key="CNBackPaperSrc_SideDeck">Drawer 5 </Item>
<Item key="CNBackPaperSrc_PodDeck">Drawer 5  </Item>
<Item key="CNTrustPrint">Use Secure Printing Function of Device</Item>
<Item key="PageSize_Com10">Envelope No.10 (COM10)</Item>
</KeyTextList>
