<?xml version="1.0"?>
<KeyTextList>
<Item key="CNEnableTrustPrint">Secure Watermark Function of Device</Item>
<Item key="MediaType_RECYCLED1">Recycled Paper 1</Item>
<Item key="MediaType_RECYCLED2">Recycled Paper 2</Item>
<Item key="MediaType_RECYCLED3">Recycled Paper 3</Item>
<Item key="MediaType_RECYCLED4">Recycled Paper 4</Item>
<Item key="MediaType_PREPUNCHED1">Pre-punched Paper 1</Item>
<Item key="MediaType_PREPUNCHED2">Pre-punched Paper 2</Item>
<Item key="MediaType_HEAVY4">Heavy Paper 4</Item>
<Item key="MediaType_HEAVY5">Heavy Paper 5</Item>
<Item key="MediaType_PlainPaperL">Thin</Item>
<Item key="MediaType_TAB1">Tab Paper 1</Item>
<Item key="MediaType_TAB2">Tab Paper 2</Item>
<Item key="MediaType_1SIDECOATED1">1-sided Coated 1</Item>
<Item key="MediaType_1SIDECOATED2">1-sided Coated 2</Item>
<Item key="MediaType_1SIDECOATED3">1-sided Coated 3</Item>
<Item key="MediaType_1SIDECOATED4">1-sided Coated 4</Item>
<Item key="MediaType_1SIDECOATED5">1-sided Coated 5</Item>
<Item key="MediaType_2SIDECOATED1">2-sided Coated 1</Item>
<Item key="MediaType_2SIDECOATED2">2-sided Coated 2</Item>
<Item key="MediaType_2SIDECOATED3">2-sided Coated 3</Item>
<Item key="MediaType_2SIDECOATED4">2-sided Coated 4</Item>
<Item key="MediaType_2SIDECOATED5">2-sided Coated 5</Item>
<Item key="MediaType_EMBOSS1">Texture Paper 1</Item>
<Item key="MediaType_EMBOSS2">Texture Paper 2</Item>
<Item key="MediaType_EMBOSS3">Texture Paper 3</Item>
<Item key="MediaType_EMBOSS4">Texture Paper 4</Item>
<Item key="MediaType_EMBOSS5">Texture Paper 5</Item>
<Item key="MediaType_EMBOSS6">Texture Paper 6</Item>
<Item key="MediaType_VELLUM2">Vellum 2</Item>
<Item key="CNInterleafMediaType_RECYCLED1">Recycled Paper 1</Item>
<Item key="CNInterleafMediaType_RECYCLED2">Recycled Paper 2</Item>
<Item key="CNInterleafMediaType_RECYCLED3">Recycled Paper 3</Item>
<Item key="CNInterleafMediaType_RECYCLED4">Recycled Paper 4</Item>
<Item key="CNInterleafMediaType_PREPUNCHED1">Pre-punched Paper 1</Item>
<Item key="CNInterleafMediaType_PREPUNCHED2">Pre-punched Paper 2</Item>
<Item key="CNInterleafMediaType_HEAVY4">Heavy Paper 4</Item>
<Item key="CNInterleafMediaType_HEAVY5">Heavy Paper 5</Item>
<Item key="CNInterleafMediaType_PlainPaperL">Thin</Item>
<Item key="CNInterleafMediaType_1SIDECOATED1">1-sided Coated 1</Item>
<Item key="CNInterleafMediaType_1SIDECOATED2">1-sided Coated 2</Item>
<Item key="CNInterleafMediaType_1SIDECOATED3">1-sided Coated 3</Item>
<Item key="CNInterleafMediaType_1SIDECOATED4">1-sided Coated 4</Item>
<Item key="CNInterleafMediaType_1SIDECOATED5">1-sided Coated 5</Item>
<Item key="CNInterleafMediaType_2SIDECOATED1">2-sided Coated 1</Item>
<Item key="CNInterleafMediaType_2SIDECOATED2">2-sided Coated 2</Item>
<Item key="CNInterleafMediaType_2SIDECOATED3">2-sided Coated 3</Item>
<Item key="CNInterleafMediaType_2SIDECOATED4">2-sided Coated 4</Item>
<Item key="CNInterleafMediaType_2SIDECOATED5">2-sided Coated 5</Item>
<Item key="CNInterleafMediaType_EMBOSS1">Texture Paper 1</Item>
<Item key="CNInterleafMediaType_EMBOSS2">Texture Paper 2</Item>
<Item key="CNInterleafMediaType_EMBOSS3">Texture Paper 3</Item>
<Item key="CNInterleafMediaType_EMBOSS4">Texture Paper 4</Item>
<Item key="CNInterleafMediaType_EMBOSS5">Texture Paper 5</Item>
<Item key="CNInterleafMediaType_EMBOSS6">Texture Paper 6</Item>
<Item key="CNInterleafMediaType_VELLUM2">Vellum 2</Item>
<Item key="CNTrustPrint">Use Secure Watermark Function of Device</Item>
</KeyTextList>
