<?xml version="1.0"?>
<KeyTextList>
<Item key="CNSrcOption_None">None </Item>
<Item key="CNSrcOption_OptCas1">Paper Deck Unit-A1</Item>
<Item key="CNSrcOption_OptCas2">Paper Deck Unit-B1</Item>
<Item key="CNSrcOption_OptCas3">POD Deck Lite-A1</Item>
<Item key="CNSrcOption_OptCas4">Multi Drawer Paper Deck-A1</Item>
<Item key="CNFinisher_None">None </Item>
<Item key="CNFinisher_FINM1">Finisher-M1</Item>
<Item key="CNFinisher_FINN1">Finisher-N1</Item>
<Item key="CNFinisher_FINP1">Finisher-P1</Item>
<Item key="CNFinisher_FINL1">Finisher-L1</Item>
<Item key="CNFinisher_FINK1">Finisher-K1</Item>
<Item key="CNFinisher_FINK2">Finisher-K2</Item>
<Item key="CNFinisher_SFINK3">Saddle Finisher-K3</Item>
<Item key="CNFinisher_SFINK3N">Saddle Finisher-K3N</Item>
<Item key="CNFinisher_SFINK4">Saddle Finisher-K4</Item>
<Item key="CNFinisher_STKA1">Stacker-A1</Item>
<Item key="CNFinisher_SFING1">Saddle Finisher-G1</Item>
<Item key="CNFinisher_FINJ1">Finisher-J1</Item>
<Item key="CNFinisher_FinV1">Finisher-V1/V1L</Item>
<Item key="CNFinisher_FinV1_PBA1">Finisher-V1/V1L + Perfect Binder-A1</Item>
<Item key="CNFinisher_FinV1_HCSA1_PBA1">Finisher-V1/V1L + High Capacity Stacker-A1 + Perfect Binder-A1</Item>
<Item key="CNFinisher_SFinV2">Saddle Finisher-V2/V2L</Item>
<Item key="CNFinisher_SFinV2_PBA1">Saddle Finisher-V2/V2L + Perfect Binder-A1</Item>
<Item key="CNFinisher_SFinV2_HCSA1_PBA1">Saddle Finisher-V2/V2L + High Capacity Stacker-A1 + Perfect Binder-A1</Item>
<Item key="CNFinisher_HCSA1">High Capacity Stacker-A1</Item>
<Item key="CNFinisher_HCSA1_PBA1">High Capacity Stacker-A1 + Perfect Binder-A1</Item>
<Item key="CNFinisher_PBA1">Perfect Binder-A1</Item>
<Item key="CNFinisher_IN2TRAY">Inner 2way Tray</Item>
<Item key="CNFinisher_In2CT">Inner 2way Tray + Copy Tray</Item>
<Item key="CNFinisher_IN2TRAYC1">Inner 2way Tray-C1</Item>
<Item key="CNFinisher_FINP1CT">Finisher-P1 + Copy Tray</Item>
<Item key="CNFinisher_FINS1">Finisher-S1</Item>
<Item key="CNFinisher_FINS1_CT">Finisher-S1 + Copy Tray</Item>
<Item key="CNFinisher_FINS1_FT">Finisher-S1 + Finisher Tray</Item>
<Item key="CNFinisher_FINS1_CT_FT">Finisher-S1 + Copy Tray + Finisher Tray</Item>
<Item key="CNFinisher_FINQ1">Finisher-Q1</Item>
<Item key="CNFinisher_FINQ1Q3">Finisher-Q1/Q3</Item>
<Item key="CNFinisher_FINQ3">Finisher-Q3</Item>
<Item key="CNFinisher_FINQ3FT">Finisher-Q3 + Finisher Tray</Item>
<Item key="CNFinisher_SFINQ2">Saddle Finisher-Q2</Item>
<Item key="CNFinisher_SFINQ2Q4">Saddle Finisher-Q2/Q4</Item>
<Item key="CNFinisher_SFINQ4">Saddle Finisher-Q4</Item>
<Item key="CNFinisher_STAPLESTK">Stapler Stacker</Item>
<Item key="CNFinisher_7BIN">7-bin Sorter</Item>
<Item key="CNFinisher_SFINQ4FT">Saddle Finisher-Q4 + Finisher Tray</Item>
<Item key="CNFinisher_FINAE1">Finisher-AE1</Item>
<Item key="CNFinisher_FINAE1FT">Finisher-AE1 + Finisher Tray</Item>
<Item key="CNFinisher_SFINAE2">Saddle Finisher-AE2</Item>
<Item key="CNFinisher_SFINAE2FT">Saddle Finisher-AE2 + Finisher Tray</Item>
<Item key="CNFinisher_CPYTRAY">Copy Tray</Item>
<Item key="CNFinisher_MTRAY3">Multi Tray-3</Item>
<Item key="CNFinisher_OPTTRAY">Option Tray</Item>
<Item key="CNFinisher_FINE1">Finisher-E1</Item>
<Item key="CNFinisher_FINC1">Finisher-C1</Item>
<Item key="CNFinisher_SFINC2">Saddle Finisher-C2</Item>
<Item key="CNFinisher_FINU1">Finisher-U1</Item>
<Item key="CNFinisher_FINTRAY">Finisher Tray</Item>
<Item key="CNFinisher_FinX1">Finisher-X1</Item>
<Item key="CNFinisher_FinW1">Finisher-W1</Item>
<Item key="CNFinisher_SFinW2">Saddle Finisher-W2</Item>
<Item key="CNFinisher_FinZ1">Finisher-Z1</Item>
<Item key="CNFinisher_FinZ1CT">Finisher-Z1 + Copy Tray</Item>
<Item key="CNFinisher_FinY1">Finisher-Y1</Item>
<Item key="CNFinisher_SFinY2">Saddle Finisher-Y2</Item>
<Item key="CNFinisher_FINAD1">Finisher-AD1</Item>
<Item key="CNFinisher_SFINAD2">Saddle Finisher-AD2</Item>
<Item key="CNFinisher_FinAA1">Finisher-AA1</Item>
<Item key="CNFinisher_SFinAA2">Saddle Finisher-AA2</Item>
<Item key="CNFinisher_FINU2">Finisher-U2</Item>
<Item key="CNFinisher_FINU2FT">Finisher-U2 + Finisher Tray</Item>
<Item key="CNFinisher_FINR1">Finisher-R1</Item>
<Item key="CNFinisher_FINR1FT">Finisher-R1 + Finisher Tray</Item>
<Item key="CNFinisher_SFINR2">Saddle Finisher-R2</Item>
<Item key="CNFinisher_SFINR2FT">Saddle Finisher-R2 + Finisher Tray</Item>
<Item key="CNFinisher_FINAC1">Finisher-AC1</Item>
<Item key="CNFinisher_SFINAC2">Saddle Finisher-AC2</Item>
<Item key="CNFinisher_SFINN2">Saddle Finisher-N2</Item>
<Item key="CNFinisher_FINF1">Finisher-F1</Item>
<Item key="CNFinisher_SFINF2">Saddle Finisher-F2</Item>
<Item key="CNFinisher_FINT1">Finisher-T1</Item>
<Item key="CNFinisher_SFINT2">Saddle Finisher-T2</Item>
<Item key="CNFinisher_SHIFTTRAY">Shift Tray</Item>
<Item key="CNFinisher_StFinA1">Staple Finisher-A1</Item>
<Item key="CNFinisher_BFinA1">Booklet Finisher-A1</Item>
<Item key="CNFinisher_StFinB1">Staple Finisher-B1</Item>
<Item key="CNFinisher_BFinB1">Booklet Finisher-B1</Item>
<Item key="CNFinisher_IFinA1">Inner Finisher-A1</Item>
<Item key="CNFinisher_IFinA1CT">Inner Finisher-A1 + Copy Tray</Item>
<Item key="CNFinisher_IFinA1AT">Inner Finisher-A1 + Inner Finisher Additional Tray</Item>
<Item key="CNFinisher_IFinA1CTAT">Inner Finisher-A1 + Copy Tray + Inner Finisher Additional Tray</Item>
<Item key="CNFinisher_StFinC1">Staple Finisher-C1</Item>
<Item key="CNFinisher_BFinC1">Booklet Finisher-C1</Item>
<Item key="CNFinisher_STFIND1">Staple Finisher-D1</Item>
<Item key="CNFinisher_BFIND1">Booklet Finisher-D1</Item>
<Item key="CNFinisher_STFINE1">Staple Finisher-E1</Item>
<Item key="CNFinisher_BFINE1">Booklet Finisher-E1</Item>
<Item key="CNFinisher_IFINB1">Inner Finisher-B1</Item>
<Item key="CNFinisher_IFINB1AT">Inner Finisher-B1 + Inner Finisher Additional Tray</Item>
<Item key="CNFinisher_FINAF1">Staple Finisher-F1</Item>
<Item key="CNFinisher_SFINAF2">Booklet Finisher-F1</Item>
<Item key="CNFinisher_IFINC1">Inner Finisher-C1</Item>
<Item key="CNFinisher_IFINC1CT">Inner Finisher-C1 + Copy Tray</Item>
<Item key="CNFinisher_IFINC1AT">Inner Finisher-C1 + Inner Finisher Additional Tray</Item>
<Item key="CNFinisher_IFINC1CTAT">Inner Finisher-C1 + Copy Tray + Inner Finisher Additional Tray</Item>
<Item key="CNFinisher_IFIND1">Inner Finisher-D1</Item>
<Item key="CNFinisher_IFIND1AT">Inner Finisher-D1 + Inner Finisher Additional Tray</Item>
<Item key="CNFinisher_STFING1">Staple Finisher-G1</Item>
<Item key="CNFinisher_BFING1">Booklet Finisher-G1</Item>
<Item key="CNFinisher_STFINH1">Staple Finisher-H1</Item>
<Item key="Resolution_1200">1200 dpi</Item>
<Item key="Resolution_600">600 dpi</Item>
<Item key="Resolution_300">300 dpi</Item>
<Item key="CNDraftMode_Auto">Printer Default</Item>
<Item key="CNDraftMode_True">On</Item>
<Item key="CNDraftMode_False">Off</Item>
<Item key="CNSpecialPrintAdjustmentA_None">Printer Default</Item>
<Item key="CNSpecialPrintAdjustmentA_Off">Off</Item>
<Item key="CNSpecialPrintAdjustmentA_Mode1">Mode 1</Item>
<Item key="CNSpecialPrintAdjustmentA_Mode2">Mode 2</Item>
<Item key="CNSpecialPrintAdjustmentA_Mode3">Mode 3</Item>
<Item key="CNSpecialPrintAdjustmentA_Mode4">Mode 4</Item>
<Item key="CNSpecialPrintAdjustmentB_Off">Off</Item>
<Item key="CNSpecialPrintAdjustmentB_Mode1">Mode 1</Item>
<Item key="CNSpecialPrintAdjustmentB_Mode2">Mode 2</Item>
<Item key="CNSpecialPrintAdjustmentB_Mode3">Mode 3</Item>
<Item key="CNMonitorProfile_sRGBv1.20(Canon)">sRGB v1.20 (Canon)</Item>
<Item key="CNMonitorProfile_sRGBv3.0(Canon)">sRGB v3.0 (Canon)</Item>
<Item key="CNMonitorProfile_HDTVgamma1.5">Canon HDTV gamma 1.5 Monitor</Item>
<Item key="CNMonitorProfile_HDTVgamma1.8">Canon HDTV gamma 1.8 Monitor</Item>
<Item key="CNMonitorProfile_HDTVgamma2.1">Canon HDTV gamma 2.1 Monitor</Item>
<Item key="CNMonitorProfile_HDTVgamma2.4">Canon HDTV gamma 2.4 Monitor</Item>
<Item key="CNMonitorProfile_None">Printer Default</Item>
<Item key="CNMatchingMethod_Saturation">Saturation</Item>
<Item key="CNMatchingMethod_Monitor">Perceptual (Monitor Color Matched)</Item>
<Item key="CNMatchingMethod_Photographic">Perceptual (Photographic)</Item>
<Item key="CNMatchingMethod_Colorimetric">Colorimetric</Item>
<Item key="CNMatchingMethod_Vividphoto">Vivid Photo</Item>
<Item key="CNMatchingMethod_Standard">Standard</Item>
<Item key="CNMatchingMethod_None">Printer Default</Item>
<Item key="CNTonerSaving_Auto">Printer Default</Item>
<Item key="CNTonerSaving_True">On</Item>
<Item key="CNTonerSaving_False">Off</Item>
<Item key="MediaType_Auto">Auto</Item>
<Item key="MediaType_None">Printer Default</Item>
<Item key="MediaType_PlainPaper">Plain Paper</Item>
<Item key="MediaType_PlainLPaper">Plain Paper L </Item>
<Item key="MediaType_PlainPaperL">Plain Paper L</Item>
<Item key="MediaType_PlainPaperL2">Plain Paper H</Item>
<Item key="MediaType_PlainPaper3">Plain Paper 3</Item>
<Item key="MediaType_RECYCLED">Recycled Paper</Item>
<Item key="MediaType_COLOR">Color Paper</Item>
<Item key="MediaType_PREPUNCHED">Pre-punched Paper</Item>
<Item key="MediaType_LHEAD">Letterhead</Item>
<Item key="MediaType_LHEADPLAIN">Letterhead (Plain)</Item>
<Item key="MediaType_LHEADHEAVY">Letterhead (Heavy)</Item>
<Item key="MediaType_BOND">Bond Paper</Item>
<Item key="MediaType_HEAVY">Heavy Paper</Item>
<Item key="MediaType_HEAVY1">Heavy Paper 1</Item>
<Item key="MediaType_HEAVY2">Heavy Paper 2</Item>
<Item key="MediaType_HEAVY3">Heavy Paper 3</Item>
<Item key="MediaType_HEAVYL">Heavy Paper L</Item>
<Item key="MediaType_ThickPaperL">Heavy Paper L </Item>
<Item key="MediaType_ThickPaperH">Heavy Paper H</Item>
<Item key="MediaType_ohp">Transparency</Item>
<Item key="MediaType_ThickPaper">Heavy Paper </Item>
<Item key="MediaType_OHP">Transparency</Item>
<Item key="MediaType_POSTCARD">Postcard</Item>
<Item key="MediaType_LABELS">Labels</Item>
<Item key="MediaType_ENVELOPE">Envelope</Item>
<Item key="MediaType_COATED">Glossy Film</Item>
<Item key="MediaType_Postcard">Postcard</Item>
<Item key="MediaType_Envelope">Envelope</Item>
<Item key="MediaType_Postcard_L">Postcard L</Item>
<Item key="MediaType_EnvelopeH">Envelope H</Item>
<Item key="MediaType_ThickThickL">Heavy/HeavyL</Item>
<Item key="MediaType_TAB">Tab Paper</Item>
<Item key="MediaType_TAB1">Tab Paper 1</Item>
<Item key="MediaType_TAB2">Tab Paper 2</Item>
<Item key="MediaType_TRACING">Tracing Paper</Item>
<Item key="MediaType_CoatedPaper">Coated Paper</Item>
<Item key="MediaType_ROUGH">Rough Paper</Item>
<Item key="MediaType_ROUGH1">Rough Paper 1</Item>
<Item key="MediaType_ROUGH2">Rough Paper 2</Item>
<Item key="MediaType_ROUGH3">Rough Paper 3</Item>
<Item key="MediaType_GLOSSY">Glossy Paper</Item>
<Item key="MediaType_JAPANESE">Washi (Japanese Paper)</Item>
<Item key="InputSlot_Auto">Auto</Item>
<Item key="InputSlot_Manual">Multi-purpose Tray </Item>
<Item key="InputSlot_Cas1">Drawer 1</Item>
<Item key="InputSlot_Cas2">Drawer 2</Item>
<Item key="InputSlot_Cas3">Drawer 3</Item>
<Item key="InputSlot_Cas4">Drawer 4</Item>
<Item key="InputSlot_Cas5">Drawer 5</Item>
<Item key="InputSlot_Cas6">Drawer 6</Item>
<Item key="InputSlot_Cas7">Drawer 7</Item>
<Item key="InputSlot_SideDeck">Side Paper Deck</Item>
<Item key="InputSlot_Env">Envelope Feeder</Item>
<Item key="InputSlot_Env2">Envelope Feeder </Item>
<Item key="CNInterleafMediaType_Auto">Auto</Item>
<Item key="CNInterleafMediaType_None">Printer Default</Item>
<Item key="CNInterleafMediaType_PlainPaper">Plain Paper</Item>
<Item key="CNInterleafMediaType_PlainPaperL">Plain Paper L</Item>
<Item key="CNInterleafMediaType_PlainPaperL2">Plain Paper H</Item>
<Item key="CNInterleafMediaType_PlainPaper3">Plain Paper 3</Item>
<Item key="CNInterleafMediaType_RECYCLED">Recycled Paper</Item>
<Item key="CNInterleafMediaType_COLOR">Color Paper</Item>
<Item key="CNInterleafMediaType_BOND">Bond Paper</Item>
<Item key="CNInterleafMediaType_LABELS">Labels</Item>
<Item key="CNInterleafMediaType_TRACING">Tracing Paper</Item>
<Item key="CNInterleafMediaType_LHEAD">Letterhead</Item>
<Item key="CNInterleafMediaType_PREPUNCHED">Pre-punched Paper</Item>
<Item key="CNInterleafMediaType_LHEADPLAIN">Letterhead (Plain)</Item>
<Item key="CNInterleafMediaType_LHEADHEAVY">Letterhead (Heavy)</Item>
<Item key="CNInterleafMediaType_HEAVY">Heavy Paper</Item>
<Item key="CNInterleafMediaType_HEAVY1">Heavy Paper 1</Item>
<Item key="CNInterleafMediaType_HEAVY2">Heavy Paper 2</Item>
<Item key="CNInterleafMediaType_HEAVY3">Heavy Paper 3</Item>
<Item key="CNInterleafMediaType_HEAVYL">Heavy Paper L</Item>
<Item key="CNInterleafMediaType_ThickPaperH">Heavy Paper H</Item>
<Item key="CNInterleafMediaType_GLOSSY">Glossy Paper</Item>
<Item key="CNInterleafMediaType_TAB1">Tab Paper 1</Item>
<Item key="CNInterleafMediaType_TAB2">Tab Paper 2</Item>
<Item key="CNInterleafMediaType_ROUGH">Rough Paper</Item>
<Item key="CNInterleafMediaType_ROUGH1">Rough Paper 1</Item>
<Item key="CNInterleafMediaType_ROUGH2">Rough Paper 2</Item>
<Item key="CNInterleafMediaType_ROUGH3">Rough Paper 3</Item>
<Item key="CNInterleafMediaType_JAPANESE">Washi (Japanese Paper)</Item>
<Item key="OutputBin_Auto">Auto</Item>
<Item key="OutputBin_TrayA">Tray A</Item>
<Item key="OutputBin_TrayB">Tray B</Item>
<Item key="OutputBin_TrayC">Tray C</Item>
<Item key="OutputBin_Stack">Stack Compartment</Item>
<Item key="OutputBin_Tray">Output Tray</Item>
<Item key="OutputBin_SubTray">Sub-output Tray</Item>
<Item key="OutputBin_Bin1">Bin 1</Item>
<Item key="OutputBin_Bin2">Bin 2</Item>
<Item key="OutputBin_Bin3">Bin 3</Item>
<Item key="OutputBin_Bin4">Bin 4</Item>
<Item key="OutputBin_Bin5">Bin 5</Item>
<Item key="OutputBin_Bin6">Bin 6</Item>
<Item key="OutputBin_Bin7">Bin 7</Item>
<Item key="CNPlainPaperCurlCorrect_None">Printer Default</Item>
<Item key="CNPlainPaperCurlCorrect_Off">Off </Item>
<Item key="CNPlainPaperCurlCorrect_Mode1">Mode 1</Item>
<Item key="CNPlainPaperCurlCorrect_Mode2">Mode 2</Item>
<Item key="CNSpecialPrintMode_None">Printer Default</Item>
<Item key="CNSpecialPrintMode_False">Off</Item>
<Item key="CNSpecialPrintMode_True">On</Item>
<Item key="CNSpecialPrintMode_Mode1">Mode 1</Item>
<Item key="CNSpecialPrintMode_Mode2">Mode 2</Item>
<Item key="CNSpecialPrintMode_Mode3">Mode 3</Item>
<Item key="CNSpecialPrintMode_Mode4">Mode 4</Item>
<Item key="CNSpecialPrintMode_None">Printer Default</Item>
<Item key="CNSpecialPrintAdjustment_False">Off </Item>
<Item key="CNSpecialPrintAdjustment_Settings1">Special Settings 1</Item>
<Item key="CNSpecialPrintAdjustment_Settings2">Special Settings 2</Item>
<Item key="CNOutputAdjustment_True">On</Item>
<Item key="CNOutputAdjustment_False">Off</Item>
<Item key="BindEdge_Left">Long Edge (Left)</Item>
<Item key="BindEdge_Right">Long Edge (Right)</Item>
<Item key="BindEdge_Top">Short Edge (Top)</Item>
<Item key="BindEdge_Bottom">Short Edge (Bottom)</Item>
<Item key="Booklet_None">OFF</Item>
<Item key="Booklet_Left">Left Binding</Item>
<Item key="Booklet_Right">Right Binding</Item>
<Item key="Collate_False">Off  </Item>
<Item key="Collate_True">Collate </Item>
<Item key="Collate_Group">Group</Item>
<Item key="Collate_Staple">Staple</Item>
<Item key="Collate_StapleCollate">Staple &amp; Collate</Item>
<Item key="Collate_StapleGroup">Staple &amp; Group</Item>
<Item key="StapleLocation_None">No Stapling</Item>
<Item key="StapleLocation_TopLeft">Upper Left (Single)</Item>
<Item key="StapleLocation_Top">Top (Double)</Item>
<Item key="StapleLocation_TopRight">Upper Right (Single)</Item>
<Item key="StapleLocation_Left">Left (Double)</Item>
<Item key="StapleLocation_Right">Right (Double)</Item>
<Item key="StapleLocation_BottomLeft">Lower Left (Single)</Item>
<Item key="StapleLocation_Bottom">Bottom (Double)</Item>
<Item key="StapleLocation_BottomRight">Lower Right (Single)</Item>
<Item key="CNHalfFoldSetting_pattern1">Face Down + Portrait</Item>
<Item key="CNHalfFoldSetting_pattern2">Face Up + Landscape</Item>
<Item key="CNAccordionZfoldSetting_pattern1">Portrait </Item>
<Item key="CNAccordionZfoldSetting_pattern2">Landscape </Item>
<Item key="CNDoubleParallelFoldSetting_pattern1">Face Down + Portrait</Item>
<Item key="CNDoubleParallelFoldSetting_pattern2">Face Down + Landscape</Item>
<Item key="CNDoubleParallelFoldSetting_pattern3">Face Up + Portrait</Item>
<Item key="CNDoubleParallelFoldSetting_pattern4">Face Up + Landscape</Item>
<Item key="CNMultiPunch_Off">Off</Item>
<Item key="CNMultiPunch_On">On</Item>
<Item key="CNMultiPunch_PUNU2">2 Holes</Item>
<Item key="CNMultiPunch_PUNU23">2/3 Holes</Item>
<Item key="CNMultiPunch_PUNF2">2 Holes (French)</Item>
<Item key="CNMultiPunch_PUNF4">4 Holes (French)</Item>
<Item key="CNMultiPunch_PUNS4">4 Holes (Swedish)</Item>
<Item key="CNMultiPunch_PUNM">Multi Holes</Item>
<Item key="CNOutputFace_None">Printer Default</Item>
<Item key="CNOutputFace_FaceUp">Face Up (Reverse Output Order)</Item>
<Item key="CNOutputFace_FaceDown">Face Down (Normal Output Order)</Item>
<Item key="CNColorMode_Auto">Auto Detect</Item>
<Item key="CNColorMode_color">Color</Item>
<Item key="CNColorMode_mono">Black and White</Item>
<Item key="CNOHPPrintMode_None">Printer Default</Item>
<Item key="CNOHPPrintMode_Transparent">Transmissive Projector</Item>
<Item key="CNOHPPrintMode_Reflective">Reflective Projector</Item>
<Item key="CNImageRefinement_None">Printer Default</Item>
<Item key="CNImageRefinement_True">On</Item>
<Item key="CNImageRefinement_False">Off</Item>
<Item key="CNLineRefinement_None">Printer Default</Item>
<Item key="CNLineRefinement_True">On</Item>
<Item key="CNLineRefinement_False">Off</Item>
<Item key="CNFrontPrintOn_Off">None </Item>
<Item key="CNFrontPrintOn_OnlyFrontSide">Only Front Side</Item>
<Item key="CNFrontPrintOn_OnlyBackSide">Only Back Side</Item>
<Item key="CNFrontPrintOn_BothSides">Both Sides</Item>
<Item key="CNFrontPaperSrc_Manual">Multi-purpose Tray </Item>
<Item key="CNFrontPaperSrc_Cas1">Drawer 1</Item>
<Item key="CNFrontPaperSrc_Cas2">Drawer 2</Item>
<Item key="CNFrontPaperSrc_Cas3">Drawer 3</Item>
<Item key="CNFrontPaperSrc_Cas4">Drawer 4</Item>
<Item key="CNFrontPaperSrc_Sidedeck">Side Paper Deck</Item>
<Item key="CNFrontPaperSrc_InsertionUnit">Insertion Unit</Item>
<Item key="CNFrontPaperSrc_InsertionUnit1">Inserter 1</Item>
<Item key="CNFrontPaperSrc_InsertionUnit2">Inserter 2</Item>
<Item key="CNBackPrintOn_Off">None </Item>
<Item key="CNBackPrintOn_OnlyFrontSide">Only Front Side</Item>
<Item key="CNBackPrintOn_OnlyBackSide">Only Back Side</Item>
<Item key="CNBackPrintOn_BothSides">Both Sides</Item>
<Item key="CNBackPaperSrc_Manual">Multi-purpose Tray </Item>
<Item key="CNBackPaperSrc_Cas1">Drawer 1</Item>
<Item key="CNBackPaperSrc_Cas2">Drawer 2</Item>
<Item key="CNBackPaperSrc_Cas3">Drawer 3</Item>
<Item key="CNBackPaperSrc_Cas4">Drawer 4</Item>
<Item key="CNBackPaperSrc_Sidedeck">Side Paper Deck</Item>
<Item key="CNBackPaperSrc_InsertionUnit">Insertion Unit</Item>
<Item key="CNBackPaperSrc_InsertionUnit1">Inserter 1</Item>
<Item key="CNBackPaperSrc_InsertionUnit2">Inserter 2</Item>
<Item key="CNCfoldSetting_pattern1">Face Down + Portrait</Item>
<Item key="CNCfoldSetting_pattern2">Face Down + Landscape</Item>
<Item key="CNCfoldSetting_pattern3">Face Up + Portrait</Item>
<Item key="CNCfoldSetting_pattern4">Face Up + Landscape</Item>
<Item key="CNAdvancedSmoothing_None">Printer Default</Item>
<Item key="CNAdvancedSmoothing_Off">Off</Item>
<Item key="CNAdvancedSmoothing_Smooth1">Smooth 1</Item>
<Item key="CNAdvancedSmoothing_Smooth2">Smooth 2</Item>
<Item key="CNColorHalftone_None">Printer Default</Item>
<Item key="CNColorHalftone_Resolution">Resolution</Item>
<Item key="CNColorHalftone_Gradation">Gradation</Item>
<Item key="CNColorHalftone_ColorTone">Color Tone</Item>
<Item key="CNColorHalftone_pattern1">Pattern 1</Item>
<Item key="CNColorHalftone_pattern2">Pattern 2</Item>
<Item key="CNHalftone_None">Printer Default</Item>
<Item key="CNHalftone_Resolution">Resolution</Item>
<Item key="CNHalftone_Gradation">Gradation</Item>
<Item key="CNHalftone_ColorTone">Color Tone</Item>
<Item key="CNHalftone_Off">None (Solid)</Item>
<Item key="CNGlossyPlainPaperProc_None">Printer Default</Item>
<Item key="CNGlossyPlainPaperProc_False">Off </Item>
<Item key="CNGlossyPlainPaperProc_True">On </Item>
<Item key="CNSpecialSmooth_None">Printer Default</Item>
<Item key="CNSpecialSmooth_Mode1">Mode 1</Item>
<Item key="CNSpecialSmooth_Mode2">Mode 2</Item>
<Item key="CNSpecialSmooth_Mode3">Mode 3</Item>
<Item key="CNSpecialSmooth_Mode4">Mode 4</Item>
<Item key="CNSpecialSmooth_Mode5">Mode 5</Item>
<Item key="CNSpecialSmooth_Mode6">Mode 6</Item>
<Item key="CNTonerDensity_None">Printer Default</Item>
<Item key="CNTonerDensity_1">-8 (Light)</Item>
<Item key="CNTonerDensity_2">-7 (Light)</Item>
<Item key="CNTonerDensity_3">-6 (Light)</Item>
<Item key="CNTonerDensity_4">-5 (Light)</Item>
<Item key="CNTonerDensity_5">-4 (Light)</Item>
<Item key="CNTonerDensity_6">-3 (Light)</Item>
<Item key="CNTonerDensity_7">-2 (Light)</Item>
<Item key="CNTonerDensity_8">-1 (Light)</Item>
<Item key="CNTonerDensity_9">0 (Standard)</Item>
<Item key="CNTonerDensity_10">1 (Dark)</Item>
<Item key="CNTonerDensity_11">2 (Dark)</Item>
<Item key="CNTonerDensity_12">3 (Dark)</Item>
<Item key="CNTonerDensity_13">4 (Dark)</Item>
<Item key="CNTonerDensity_14">5 (Dark)</Item>
<Item key="CNTonerDensity_15">6 (Dark)</Item>
<Item key="CNTonerDensity_16">7 (Dark)</Item>
<Item key="CNTonerDensity_17">8 (Dark)</Item>
<Item key="CNLineControl_None">Printer Default</Item>
<Item key="CNLineControl_Resolution">Resolution Priority</Item>
<Item key="CNLineControl_Gradation">Gradation Priority</Item>
<Item key="CNJobExecMode_print">Print</Item>
<Item key="CNJobExecMode_secured">Secured Print</Item>
<Item key="CNJobExecMode_store">Store</Item>
<Item key="CNJobExecMode_hold">Hold</Item>
<Item key="CNSharpness_None">Printer Default</Item>
<Item key="CNSharpness_-3">-3 (Low)</Item>
<Item key="CNSharpness_-2">-2 (Low)</Item>
<Item key="CNSharpness_-1">-1 (Low)</Item>
<Item key="CNSharpness_0">0 (Standard)</Item>
<Item key="CNSharpness_1">1 (High)</Item>
<Item key="CNSharpness_2">2 (High)</Item>
<Item key="CNSharpness_3">3 (High)</Item>
<Item key="CNSmallSizeCurl_None">Printer Default</Item>
<Item key="CNSmallSizeCurl_True">On </Item>
<Item key="CNSmallSizeCurl_False">Off </Item>
<Item key="PageSize_Letter">Letter</Item>
<Item key="PageSize_11x17">11x17</Item>
<Item key="PageSize_Ledger">11x17 </Item>
<Item key="PageSize_Legal">Legal</Item>
<Item key="PageSize_Statement">Statement</Item>
<Item key="PageSize_Executive">Executive</Item>
<Item key="PageSize_A6">A6</Item>
<Item key="PageSize_A5">A5</Item>
<Item key="PageSize_B5">B5</Item>
<Item key="PageSize_A4">A4</Item>
<Item key="PageSize_B4">B4</Item>
<Item key="PageSize_A3">A3</Item>
<Item key="PageSize_Postcard">Postcard</Item>
<Item key="PageSize_dbl_postcard">Reply Postcard</Item>
<Item key="PageSize_4x_postcard">4 on 1 Postcard</Item>
<Item key="PageSize_jenv_you2">Envelope YOUGATA 2</Item>
<Item key="PageSize_jenv_you4">Envelope YOUGATA 4</Item>
<Item key="PageSize_jenv_you_chou3">Envelope YOUGATANAGA 3</Item>
<Item key="PageSize_jenv_kaku2">Envelope KAKUGATA 2</Item>
<Item key="PageSize_jenv_kaku4">Envelope KAKUGATA 4</Item>
<Item key="PageSize_jenv_chou2">Envelope NAGAGATA 2</Item>
<Item key="PageSize_jenv_chou3">Envelope NAGAGATA 3</Item>
<Item key="PageSize_Monarch">Envelope Monarch</Item>
<Item key="PageSize_Com10">Envelope COM10</Item>
<Item key="PageSize_dl_envelope">Envelope DL</Item>
<Item key="PageSize_Envelope_C5">Envelope C5</Item>
<Item key="PageSize_Envelope_B5">Envelope B5</Item>
<Item key="PageSize_SRA3">SRA3</Item>
<Item key="PageSize_12x18">12x18</Item>
<Item key="PageSize_13x19">13x19</Item>
<Item key="PageSize_Foolscap">Foolscap</Item>
<Item key="PageSize_Index_3x5">Index Card</Item>
<Item key="PageSize_16K">16K</Item>
<Item key="PageSize_8K">8K</Item>
<Item key="BindEdge_L_Left">Long Edge (Top)</Item>
<Item key="BindEdge_L_Right">Long Edge (Bottom)</Item>
<Item key="BindEdge_L_Top">Short Edge (Right)</Item>
<Item key="BindEdge_L_Bottom">Short Edge (Left)</Item>
<Item key="BindEdge_R_Left">Long Edge (Right)</Item>
<Item key="BindEdge_R_Right">Long Edge (Left)</Item>
<Item key="BindEdge_R_Top">Short Edge (Bottom)</Item>
<Item key="BindEdge_R_Bottom">Short Edge (Top)</Item>
<Item key="BindEdge_RL_Left">Long Edge (Bottom)</Item>
<Item key="BindEdge_RL_Right">Long Edge (Top)</Item>
<Item key="BindEdge_RL_Top">Short Edge (Left)</Item>
<Item key="BindEdge_RL_Bottom">Short Edge (Right)</Item>
<Item key="Booklet_L_Left">Top Binding</Item>
<Item key="Booklet_L_Right">Bottom Binding</Item>
<Item key="Booklet_R_Left">Right Binding</Item>
<Item key="Booklet_R_Right">Left Binding</Item>
<Item key="Booklet_RL_Left">Bottom Binding</Item>
<Item key="Booklet_RL_Right">Top Binding</Item>
<Item key="StapleLocation_L_None">No Stapling</Item>
<Item key="StapleLocation_L_TopLeft">Upper Right (Single)</Item>
<Item key="StapleLocation_L_Top">Right (Double)</Item>
<Item key="StapleLocation_L_TopRight">Lower Right (Single)</Item>
<Item key="StapleLocation_L_Left">Top (Double)</Item>
<Item key="StapleLocation_L_Right">Bottom (Double)</Item>
<Item key="StapleLocation_L_BottomLeft">Upper Left (Single)</Item>
<Item key="StapleLocation_L_Bottom">Left (Double)</Item>
<Item key="StapleLocation_L_BottomRight">Lower Left (Single)</Item>
<Item key="StapleLocation_R_None">No Stapling</Item>
<Item key="StapleLocation_R_TopLeft">Lower Right (Single)</Item>
<Item key="StapleLocation_R_Top">Bottom (Double)</Item>
<Item key="StapleLocation_R_TopRight">Lower Left (Single)</Item>
<Item key="StapleLocation_R_Left">Right (Double)</Item>
<Item key="StapleLocation_R_Right">Left (Double)</Item>
<Item key="StapleLocation_R_BottomLeft">Upper Right (Single)</Item>
<Item key="StapleLocation_R_Bottom">Top (Double)</Item>
<Item key="StapleLocation_R_BottomRight">Upper Left (Single)</Item>
<Item key="StapleLocation_RL_None">No Stapling</Item>
<Item key="StapleLocation_RL_TopLeft">Lower Left (Single)</Item>
<Item key="StapleLocation_RL_Top">Left (Double)</Item>
<Item key="StapleLocation_RL_TopRight">Upper Left (Single)</Item>
<Item key="StapleLocation_RL_Left">Bottom (Double)</Item>
<Item key="StapleLocation_RL_Right">Top (Double)</Item>
<Item key="StapleLocation_RL_BottomLeft">Lower Right (Single)</Item>
<Item key="StapleLocation_RL_Bottom">Right (Double)</Item>
<Item key="StapleLocation_RL_BottomRight">Upper Right (Single)</Item>
<Item key="number-up_1 Page per Sheet">1 Page per Sheet</Item>
<Item key="number-up_2 Pages per Sheet">2 Pages per Sheet</Item>
<Item key="number-up_4 Pages per Sheet">4 Pages per Sheet</Item>
<Item key="number-up_6 Pages per Sheet">6 Pages per Sheet</Item>
<Item key="number-up_9 Pages per Sheet">9 Pages per Sheet</Item>
<Item key="number-up_16 Pages per Sheet">16 Pages per Sheet</Item>
<Item key="CNFoldSetting_None">Off </Item>
<Item key="CNFoldSetting_Z-fold">Z-fold</Item>
<Item key="CNFoldSetting_C-fold">C-fold</Item>
<Item key="CNFoldSetting_Half Fold">Half Fold</Item>
<Item key="CNFoldSetting_Accordion Z-fold">Accordion Z-fold</Item>
<Item key="CNFoldSetting_Double Parallel Fold">Double Parallel Fold</Item>
<Item key="CNSaddleSetting_None">None </Item>
<Item key="CNSaddleSetting_Fold Only">Fold Only</Item>
<Item key="CNSaddleSetting_Fold + Saddle Stitch">Fold + Saddle Stitch</Item>
<Item key="CNSaddleSetting_Fold + Saddle Stitch + Trim">Fold + Saddle Stitch + Trim</Item>
<Item key="CNSaddleSetting_Saddle Stitch">Saddle Stitch</Item>
<Item key="CNSaddleSetting_Saddle Stitch + Trim">Saddle Stitch + Trim</Item>
<Item key="CNPrintStyle_1-sided Printing">1-sided Printing</Item>
<Item key="CNPrintStyle_2-sided Printing">2-sided Printing</Item>
<Item key="CNPrintStyle_Booklet Printing">Booklet Printing</Item>
<Item key="ShiftRange">mm (%d to %d)</Item>
<Item key="ShiftRange_d">mm (%.1f to %.1f)</Item>
<Item key="CorrectRange">mm (%.2f to %.2f)</Item>
<Item key="BoxID">0 to %d</Item>
<Item key="GutterValue_d">in (0.0 to %.1f)</Item>
<Item key="GutterValue">mm (0 to %d)</Item>
<Item key="OffsetRange">(1 to %d)</Item>
<Item key="TrimRange">mm (%.1f to %.1f) </Item>
<Item key="Halftone">Halftones:</Item>
<Item key="BWHalftone">B &amp; W Halftones:</Item>
</KeyTextList>
